# Generated by Django 2.1.5 on 2019-02-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='phone',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
