# Generated by Django 2.1.5 on 2019-02-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0002_property_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
