# Generated by Django 2.1.5 on 2019-02-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0003_auto_20190221_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='desc',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='price',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='subtitle',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='title',
            new_name='type',
        ),
        migrations.AddField(
            model_name='property',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
