# Generated by Django 2.1.5 on 2019-02-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0004_auto_20190222_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.CharField(default='sdada', max_length=100),
            preserve_default=False,
        ),
    ]
