# Generated by Django 2.1.5 on 2019-02-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0005_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_price',
            field=models.FloatField(),
        ),
    ]
