# Generated by Django 2.1.5 on 2019-02-22 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0006_auto_20190222_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
    ]
