# Generated by Django 2.1.5 on 2019-02-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0008_auto_20190223_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
